trigger:
  paths:
    include:
      - package.json
      - azure-pipelines-build-base.yml

variables:
  - template: variables.yml

resources:
  repositories:
    - repository: templates
      type: github
      name: decentralized-cloud/templates
      endpoint: decentralized-cloud

name: $(GitVersion.SemVer)

stages:
  - stage: Build
    jobs:
      - template: build/build-test-publish.yml@templates
        parameters:
          version: "latest"
          vmImage: ${{ variables.linuxVmImage }}
          shouldBuildContract: false
          shouldPublishServiceDockerImage: true
          shouldTestPublishResult: false
          shouldPublishHelmChartAsArtifact: false
          shouldPublishHelmChart: false
          dockerContainerRegistry: ${{ variables.dockerContainerRegistry }}
          dockerRepositoryName: ${{ variables.dockerRepositoryNameBuildBase }}
          dockerBuildFilePath: ${{ variables.dockerBuildBaseFilePath }}
          dockerBuildContext: ${{ variables.dockerBuildContext }}
